alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
drop table if exists employe;
drop table if exists phase;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
alter table phase drop foreign key FK183cbjgh92yt6ho2x5h9vnd4d;
alter table phase_employe drop foreign key FKfs6vtxxx4ovecspxrjehb339l;
alter table phase_employe drop foreign key FKmmplemy08aik3gp8lhhho41xm;
drop table if exists employe;
drop table if exists phase;
drop table if exists phase_employe;
drop table if exists projet;
